---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hierarchy.subns.org
  resources:
  - subnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hierarchy.subns.org
  resources:
  - subnamespaces/finalizers
  verbs:
  - update
- apiGroups:
  - hierarchy.subns.org
  resources:
  - subnamespaces/status
  verbs:
  - get
  - patch
  - update
